name: cache
version: 0.1.0
description: Implementations of common cache replacement algorithms.
repository: https://github.com/happy-san/dart-cache
issue_tracker: https://github.com/happy-san/dart-cache/issues

environment:
  sdk: ">=2.17.5 <3.0.0"

dev_dependencies:
  test: ^1.20.1
  lints: ^1.0.1
