name: cacher
version: 0.1.2
description: Implementations of common cache replacement algorithms. Includes LRU, TLRU, LFU.
repository: https://github.com/happy-san/dart-cacher
issue_tracker: https://github.com/happy-san/dart-cacher/issues

environment:
  sdk: ">=2.17.5 <4.0.0"

dev_dependencies:
  test: ^1.20.1
  lints: ^1.0.1
